### PR TITLE
Update EventEmitter.js

### PR DESCRIPTION
**Pull request by kantorcodes**
---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

The import for latest versions of react is incorrect and throws an error. The new file is _EventEmitter.js

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### CODE REVIEW

**Comment by ErnoW** [comment]
What exact error do you get? This seems to be an issue with react-native v0.64+
Ideally we want to support versions below and above this version.

Does this solution also work in your case?
```
  let EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');
  if (EventEmitter.default) {
    EventEmitter = EventEmitter.default;
  }
```

**Comment by kantorcodes** [comment]
> What exact error do you get? This seems to be an issue with react-native v0.64+ Ideally we want to support versions below and above this version.
> 
> Does this solution also work in your case?
> 
> ```
>   let EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');
>   if (EventEmitter.default) {
>     EventEmitter = EventEmitter.default;
>   }
> ```
> 
> For reference, that is how Parse solved this issue: [parse-community/Parse-SDK-JS#1381](https://github.com/parse-community/Parse-SDK-JS/pull/1381)

Yes, this works as well. Can we merge that in?

**Comment by kantorcodes** [comment]
> What exact error do you get? This seems to be an issue with react-native v0.64+ Ideally we want to support versions below and above this version.
> 
> Does this solution also work in your case?
> 
> ```
>   let EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');
>   if (EventEmitter.default) {
>     EventEmitter = EventEmitter.default;
>   }
> ```
> 
> For reference, that is how Parse solved this issue: [parse-community/Parse-SDK-JS#1381](https://github.com/parse-community/Parse-SDK-JS/pull/1381)

Updated to your recommended solution

**Review by ErnoW — APPROVED** [review]

**Comment by ErnoW** [comment]
Thanks a lot @kantorcodes

**Pull request merged**
