### PR TITLE
test: add scenario based integration test to balance and token in evmApi

### PR DESCRIPTION
**Pull request by FedericoAmura**
---
name: 'Scenario integration test for evmApi balance and token'
about: This PR adds scenario based integration test to balance and token endpoints of the evmApi
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### CODE REVIEW

**Comment by b4rtaz** [comment]
@FedericoAmura the build step fails.

**Review by sogunshola — COMMENTED** [review]
build fails

**Review by sogunshola — COMMENTED** [review]
Looks good. We just need to resolve conflict.

**Comment by FedericoAmura** [comment]
> Looks good. We just need to resolve conflict.

Had to fix types in the testing framework too. Now it should be ready!

**Review by sogunshola — APPROVED** [review]

**Pull request merged**
