### PR TITLE
[Streams] Fix Unindexed Event Parsing

### PR DESCRIPTION
**Pull request by blockframeio**
---
name: [Streams] Fix Unindexed Event Parsing
about: We discovered that log parsing for Moralis Streams was failing for an event we are tracking with an unindexed uint256[] argument.
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

We discovered that parsing for Moralis Streams was failing for an event we are tracking with an unindexed uint256[] argument.

Related issue: N/A

### Solution Description

We fixed the issue by modifying the `LogParser` class to handle unindexed event parameters correctly. Specifically, if the param is unindexed, then we use the argument's index to access the value as opposed to the argument's name. Otherwise, the behavior is unmodified.

This fix will ensure that Moralis Streams can correctly parse events with unindexed parameters, and will prevent similar issues we faced from occurring in the future.

### CODE REVIEW

**Comment by b4rtaz** [comment]
Could you share an example of the transaction with this problem (transactionHash)?

**Comment by blockframeio** [comment]
> Could you share an example of the transaction with this problem (transactionHash)?


https://goerli.etherscan.io/tx/0x13ff9847e889923ac0b4e6a2e62508825293f744e856dddda441732e28498029

**Comment by b4rtaz** [comment]
> https://goerli.etherscan.io/tx/0x13ff9847e889923ac0b4e6a2e62508825293f744e856dddda441732e28498029

Could you share the ABI for this smart contract?

**Review by b4rtaz — APPROVED** [review]

**Comment by b4rtaz** [comment]
@blockframeio Thanks for your contribution!

**Pull request merged**
