### PR TITLE
chore(evmapi): change to scenario based tests

### PR DESCRIPTION
**Pull request by sogunshola**
---
name: EVMAPI test
about: covert transactions and events test to scenario based tests
---

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### CODE REVIEW

**Review by b4rtaz — DISMISSED** [review]
The build crashes. Furthermore it's fine.

**Comment by sogunshola** [comment]
> The build crashes. Furthermore it's fine.

@b4rtaz I split the test in `setup.ts` so test can run properly. We will remove this when all tests have been converted.

Only issue now is that Eunice and Federico have to sync with this as well as it affects them. What do you think? any better approach?

**Comment by b4rtaz** [comment]
> Only issue now is that Eunice and Federico have to sync with this as well as it affects them. What do you think? any better approach?

I don't see a better option. We need to sync with these changes.

**Comment by b4rtaz** [comment]
@sogunshola You may notify them.

**Pull request merged**
