### PR TITLE
feat: add types to parse streams webhook data

### PR DESCRIPTION
**Pull request by ErnoW**
---
name: 'Pull request'
about: A new pull request
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### CODE REVIEW

**Comment by b4rtaz** [comment]
I wonder, maybe we should move streams types (EvmStream, EvmStreamResult etc) to a new package: `@moralisweb3/common-streams`. Why common? Because if I need to transfer some value from the back-end side to the front-end side we should create these types as a "common" side.

**Comment by ErnoW** [comment]
> I wonder, maybe we should move streams types (EvmStream, EvmStreamResult etc) to a new package: `@moralisweb3/common-streams`. Why common? Because if I need to transfer some value from the back-end side to the front-end side we should create these types as a "common" side.

Interesting point. Do you think there will be any use-cases to use these types directly in the client? I think that this feature is mostly backend-only, and that the frontend will used partial data from this, mainly via specific endpoints/database lookups.

If there is no use-case then I'd prefer to keep it simple and contained in the streams package.

**Comment by b4rtaz** [comment]
> Interesting point. Do you think there will be any use-cases to use these types directly in the client?

I'm not sure. But I can imagine that use-case.

Basically when the beta will be merged, **all SDK types** will be front-end/back-end compatible. If we don't move streams types to the common side, then we have an exception for the new approach.

**Comment by ErnoW** [comment]
True I will move it for consistency sake

**Comment by ErnoW** [comment]
@b4rtaz Moved everything in common-streams-utils

Also note, probably for your refactoring, you need the changes in `jest.config.js` in order to resolve tests correctly when we have packages in subfolders inside `/packages`

**Review by b4rtaz — APPROVED** [review]

**Pull request merged**
